export const DEFAULT_ALLOW_AUTO_REBIND = false
export const DEFAULT_AUTO_REBIND_COOLDOWN_MINUTES = 24 * 60
export const DEFAULT_AUTO_REBIND_MAX_COUNT = 0
export const AUTO_REBIND_COOLDOWN_MINUTES_MIN = 0
export const AUTO_REBIND_COOLDOWN_MINUTES_MAX = 30 * 24 * 60
export const AUTO_REBIND_MAX_COUNT_MIN = 0
export const AUTO_REBIND_MAX_COUNT_MAX = 9999
